name: action

on:
  push:
    branches:
    - 'main'
  pull_request:

permissions:
  contents: read
  pull-requests: read



jobs:
  build:
    runs-on: Linux
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER}}
        port: 22
        script: git@github.com:theclash8/aws_course_cicd.git -C /var/www/html
                 
